monday_days: &monday_days
  - start_day: 14/09/2026
  - start_day: 21/09/2026
  - start_day: 28/09/2026
  - start_day: 05/10/2026
  - start_day: 12/10/2026
  - start_day: 02/11/2026
  - start_day: 09/11/2026
  - start_day: 16/11/2026
  - start_day: 23/11/2026
  - start_day: 30/11/2026
  - start_day: 07/12/2026
  - start_day: 14/12/2026
  - start_day: 04/01/2027
  - start_day: 11/01/2027
  - start_day: 18/01/2027
  - start_day: 25/01/2027
  - start_day: 01/02/2027
  - start_day: 08/02/2027
  - start_day: 15/02/2027
  - start_day: 08/03/2027
  - start_day: 15/03/2027
  - start_day: 22/03/2027
  - start_day: 29/03/2027
  - start_day: 05/04/2027
  - start_day: 12/04/2027
  - start_day: 03/05/2027
  - start_day: 10/05/2027
  - start_day: 17/05/2027
  - start_day: 24/05/2027
  - start_day: 31/05/2027

tuesday_days: &tuesday_days
  - start_day: 15/09/2026
  - start_day: 22/09/2026
  - start_day: 29/09/2026
  - start_day: 06/10/2026
  - start_day: 13/10/2026
  - start_day: 03/11/2026
  - start_day: 10/11/2026
  - start_day: 17/11/2026
  - start_day: 24/11/2026
  - start_day: 01/12/2026
  - start_day: 08/12/2026
  - start_day: 15/12/2026
  - start_day: 05/01/2027
  - start_day: 12/01/2027
  - start_day: 19/01/2027
  - start_day: 26/01/2027
  - start_day: 02/02/2027
  - start_day: 09/02/2027
  - start_day: 16/02/2027
  - start_day: 09/03/2027
  - start_day: 16/03/2027
  - start_day: 23/03/2027
  - start_day: 30/03/2027
  - start_day: 06/04/2027
  - start_day: 13/04/2027
  - start_day: 04/05/2027
  - start_day: 11/05/2027
  - start_day: 18/05/2027
  - start_day: 25/05/2027
  - start_day: 01/06/2027

wednesday_days: &wednesday_days
  - start_day: 16/09/2026
  - start_day: 23/09/2026
  - start_day: 30/09/2026
  - start_day: 07/10/2026
  - start_day: 14/10/2026
  - start_day: 04/11/2026
  - start_day: 11/11/2026
  - start_day: 18/11/2026
  - start_day: 25/11/2026
  - start_day: 02/12/2026
  - start_day: 09/12/2026
  - start_day: 16/12/2026
  - start_day: 06/01/2027
  - start_day: 13/01/2027
  - start_day: 20/01/2027
  - start_day: 27/01/2027
  - start_day: 03/02/2027
  - start_day: 10/02/2027
  - start_day: 17/02/2027
  - start_day: 10/03/2027
  - start_day: 17/03/2027
  - start_day: 24/03/2027
  - start_day: 31/03/2027
  - start_day: 07/04/2027
  - start_day: 14/04/2027
  - start_day: 05/05/2027
  - start_day: 12/05/2027
  - start_day: 19/05/2027
  - start_day: 26/05/2027
  - start_day: 02/06/2027

thursday_days: &thursday_days
  - start_day: 17/09/2026
  - start_day: 24/09/2026
  - start_day: 01/10/2026
  - start_day: 08/10/2026
  - start_day: 15/10/2026
  - start_day: 05/11/2026
  - start_day: 12/11/2026
  - start_day: 19/11/2026
  - start_day: 26/11/2026
  - start_day: 03/12/2026
  - start_day: 10/12/2026
  - start_day: 17/12/2026
  - start_day: 07/01/2027
  - start_day: 14/01/2027
  - start_day: 21/01/2027
  - start_day: 28/01/2027
  - start_day: 04/02/2027
  - start_day: 11/02/2027
  - start_day: 18/02/2027
  - start_day: 11/03/2027
  - start_day: 18/03/2027
  - start_day: 25/03/2027
  - start_day: 01/04/2027
  - start_day: 08/04/2027
  - start_day: 15/04/2027
  - start_day: 06/05/2027
  - start_day: 13/05/2027
  - start_day: 20/05/2027
  - start_day: 27/05/2027
  - start_day: 03/06/2027

holiday_training_days: &holiday_training_days
  - start_day: 23/10/2025
  - start_day: 30/10/2025
  - start_day: 13/11/2025
  - start_day: 19/02/2027
  - start_day: 26/02/2026
  - start_day: 16/04/2026
  - start_day: 23/04/2026

credentials_file: credentials.bcs.json
categories:

  #
  # Level 3
  #
  initiations_level3:
    calendar: c_9a5896738f84440f8dfeeb5e4336b6c7fe98e52d46001ede08c6bbd4db9f96f3@group.calendar.google.com
    default:
      title: "[Rennes][BCS] Initiation + Soirée 100% WCS"
      location: LEVEL3, 1 rue Jeanne Malivel, Val D'Orson, 35770, 35770 Vern-sur-Seiche, France
      duration: 285 # 4h45 in minutes
      start_time: 20h00
      description: |
        Venez découvrir le West Coast Swing le temps d'une initiation, et pratiquer avec la communauté pendant la soirée qui suit.
        Seul·e ou à plusieurs, venez découvrir votre future activité !

        Initiation (20h - 21h30) + Soirée (21h30 - 00h45) -  6€, 1 conso offerte.

        Inscription sur https://breizhcoastswing.fr/level3

    items:
      - start_day: 29/08/2026
      - start_day: 12/09/2026

  ateliers_level3:
    calendar: c_9a5896738f84440f8dfeeb5e4336b6c7fe98e52d46001ede08c6bbd4db9f96f3@group.calendar.google.com
    default:
      title: "[Rennes][BCS] Atelier + Soirée 100% WCS"
      location: LEVEL3, 1 rue Jeanne Malivel, Val D'Orson, 35770, 35770 Vern-sur-Seiche, France
      duration: 285 # 4h45 in minutes
      start_time: 20h00
      description: |
        Atelier (20h - 21h30) + Soirée (21h30 - 00h45) -  10€, 1 conso offerte. Soirée seule à 6€ avec une conso.

        Informations sur les niveaux / thèmes à venir.

        Inscription sur https://breizhcoastswing.fr/level3
    items:
      - start_day: 07/11/2026
      - start_day: 13/02/2027
      - start_day: 24/04/2027

  soiree_level3: # Dans le cadre des journées avec Antoine & Océane
    calendar: c_9a5896738f84440f8dfeeb5e4336b6c7fe98e52d46001ede08c6bbd4db9f96f3@group.calendar.google.com
    default:
      title: "[Rennes][BCS] Soirée 100% WCS"
      location: LEVEL3, 1 rue Jeanne Malivel, Val D'Orson, 35770, 35770 Vern-sur-Seiche, France
      duration: 285 # 4h45 in minutes
      start_time: 20h00
      description: |
        Soirée (21h30 - 00h45) -  6€, 1 conso offerte.

        Inscription sur https://breizhcoastswing.fr/level3
    items:
      - start_day: 17/10/2026
      - start_day: 16/01/2027
      - start_day: 20/03/2027
      - start_day: 22/05/2027

  journee_antoine_oceane: # Dans le cadre des journées avec Antoine & Océane
    calendar: c_9a5896738f84440f8dfeeb5e4336b6c7fe98e52d46001ede08c6bbd4db9f96f3@group.calendar.google.com
    default:
      title: "[Rennes][BCS] Journée ateliers"
      location: Rennes
      duration: 360 # 6h00 in minutes
      start_time: 15h00
      description: |
        Ateliers sur plusieurs niveaux avec intervenant·es extérieur·es.

        Informations (niveaux, horaires exacts) à venir.
    items:
      - start_day: 17/10/2026
      - start_day: 16/01/2027
      - start_day: 20/03/2027
      - start_day: 22/05/2027


  #
  # Lundi
  #
  cours_n2_lundi:
    calendar: c_b5bb680aae8d9309b3b48cc3a6c24dbbcf9c3a9e21b951b035a23407c9fdac4d@group.calendar.google.com
    default:
      title: Cours niveau 2 - Lundi
      location: La Cabane, 12 Rte des Parcs Quercie, 35510 Cesson-Sévigné, France
      duration: 60
      start_time: 19h15
      description: |
        Cours niveau 2
        Ce cours est suivi de 15 minutes de pratique en commun avec le niveau 3.

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *monday_days

  cours_n3_lundi:
    calendar: c_59ee966ce6ec0eb0043366869306fd38e29a9309280a5fa315c2d13e44be8a70@group.calendar.google.com
    default:
      title: Cours niveau 3 - Lundi
      location: La Cabane, 12 Rte des Parcs Quercie, 35510 Cesson-Sévigné, France
      duration: 60
      start_time: 20h30
      description: |
        Cours niveau 3
        Ce cours est précédé de 15 minutes de pratique en commun avec le niveau 2.
        Vous êtes encouragé·e·s à arriver dès 20h15 !

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *monday_days

  #
  # Mardi
  #
  cours_n1_mardi:
    calendar: c_2cccf505e636ee3a357a381b7ee1ad1b8e25d14fcbca9498928356b3de514b0c@group.calendar.google.com
    default:
      title: Cours niveau 1 - Mardi
      location: Maison de Quartier La Touche, 6 Rue Cardinal Paul Gouyon, 35000 Rennes, France
      duration: 60
      start_time: 19h15
      description: |
        Cours niveau 1
        Ce cours est suivi de 15 minutes de pratique en commun avec le niveau 3.

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *tuesday_days

  cours_n3_mardi:
    calendar: c_35650dd62f4cdcfe486dcfe1fd483ecdc662279e7dab49ee9363bd1beb127fee@group.calendar.google.com
    default:
      title: Cours niveau 3 - Mardi
      location: Maison de Quartier La Touche, 6 Rue Cardinal Paul Gouyon, 35000 Rennes, France
      duration: 60
      start_time: 20h30
      description: |
        Cours niveau 3
        Ce cours est précédé de 15 minutes de pratique en commun avec le niveau 1.
        Vous êtes encouragé·e·s à arriver dès 20h15 !

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *tuesday_days

  cours_n3_chore_mardi:
    calendar: c_78df50123aed593ccac54f57c0d49f2ad6dbda434c6d026065e0f7c4c2244a62@group.calendar.google.com
    default:
      title: Cours choregraphie niveau 3+ - Mardi
      location: Maison de Quartier La Touche, 6 Rue Cardinal Paul Gouyon, 35000 Rennes, France
      duration: 60
      start_time: 21h30
      description: |
        Cours choregraphie niveau 3+ (au moins fait le niveau 3 une année entière).

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *tuesday_days

  #
  # Mercredi
  #
  cours_n1_mercredi:
    calendar: c_882abc9dc3d2cafbd3a29c865059a50b9b285736d0708e8156a726498d438b94@group.calendar.google.com
    default:
      title: Cours niveau 1 - Mercredi
      location: Avenir de Rennes, 47 bis Rue Papu, 35000 Rennes, France
      duration: 60
      start_time: 21h00
      description: |
        Cours niveau 1

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *wednesday_days

  cours_approf_2_3_mercredi:
    calendar: c_e22135a2f72df9f0a9c5e13a4320fd52b50ee4b9d289d3b3862d0166ca71c92b@group.calendar.google.com
    default:
      title: Cours approfondissement n2 & n3 - Mercredi
      location: Association du Bourg l'Évêque, 16 Rue Papu, 35000 Rennes, France
      duration: 60
      start_time: 21h15
      description: |
        Cours approfondissement n2 & n3. Pour les personnes en niveau 2 ou en première année de niveau 3.
        /!\ Ce cours est en Salle 5 (1er étage du batiment au fond de la cour) de la Maison de Quartier du Bourg l'Évêque, et non en salle SMAGUE (celle du jeudi).

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *wednesday_days

  cours_n2_mercredi:
    calendar: c_7c9177815e59230da75c64630e7179019b1102a7429c7552bf4fbc59de463013@group.calendar.google.com
    default:
      title: Cours niveau 2 - Mercredi
      location: Avenir de Rennes, 47 bis Rue Papu, 35000 Rennes, France
      duration: 60
      start_time: 20h00
      description: |
        Cours niveau 2

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *wednesday_days

  cours_n4_mercredi:
    calendar: c_ecc63465282d2b033399cffc03699e5fee0a094d8b6a85cfadc3b96f39447f53@group.calendar.google.com
    default:
      title: Cours niveau 4 - Mercredi
      location: Avenir de Rennes, 47 bis Rue Papu, 35000 Rennes, France
      duration: 60
      start_time: 19h00
      description: |
        Cours niveau 4

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *wednesday_days

  #
  # Jeudi
  #
  entrainement_jeudi_annee:
    calendar: c_27c826c3086f4de1829bac9712eaf60fcca9169438715e1d294e8ee1344fb382@group.calendar.google.com
    default: &entrainement_jeudi
      title: Entrainement libre - Jeudi
      location: Association du Bourg l'Évêque, 16 Rue Papu, 35000 Rennes, France
      duration: 120
      start_time: 20h15
      description: |
        Session de 2h d'entrainement libre ouvert aux adhérent·e·s.
        Ce créneau n'est pas une pratique mais permet à chacun·e de venir s'entrainer sur le sujet qu'iel souhaite.
        Il est recommandé de s'organiser en amont avec d'autres personnes pour s'assurer d'avoir du monde avec qui s'entrainer.

        Entrainement en salle Smague (à gauche en entrant)

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *thursday_days

  #
  # Dimanche
  #
  # ateliers_dimanche:
  #   calendar: c_824934c952358d37e6b402c902b4525e1d893401546ebf686b98eb834359446c@group.calendar.google.com
  #   default:
  #     title: Ateliers - Dimanche
  #     location: Rennes
  #     duration: 180
  #     start_time: 14h00
  #     description: |
  #       2 ateliers à thématique variable 1 dimanche par mois.

  #       Informations (niveaux, horaires exacts) à venir.

  # entrainement_jeudi_vacances:
  #   calendar: c_27c826c3086f4de1829bac9712eaf60fcca9169438715e1d294e8ee1344fb382@group.calendar.google.com
  #   default:
  #     <<: *entrainement_jeudi
  #   items: *holiday_training_days
