tuesday_days: &tuesday_days
  - start_day: 16/09/2025
  - start_day: 23/09/2025
  - start_day: 30/09/2025
  - start_day: 07/10/2025
  - start_day: 14/10/2025
  - start_day: 04/11/2025
  - start_day: 18/11/2025
  - start_day: 25/11/2025
  - start_day: 02/12/2025
  - start_day: 09/12/2025
  - start_day: 16/12/2025
  - start_day: 06/01/2026
  - start_day: 13/01/2026
  - start_day: 20/01/2026
  - start_day: 27/01/2026
  - start_day: 03/02/2026
  - start_day: 10/02/2026
  - start_day: 03/03/2026
  - start_day: 10/03/2026
  - start_day: 17/03/2026
  - start_day: 24/03/2026
  - start_day: 31/03/2026
  - start_day: 07/04/2026
  - start_day: 28/04/2026
  - start_day: 05/05/2026
  - start_day: 12/05/2026
  - start_day: 19/05/2026
  - start_day: 26/05/2026
  - start_day: 02/06/2026
  - start_day: 09/06/2026

wednesday_days: &wednesday_days
  - start_day: 17/09/2025
  - start_day: 24/09/2025
  - start_day: 01/10/2025
  - start_day: 08/10/2025
  - start_day: 15/10/2025
  - start_day: 05/11/2025
  - start_day: 19/11/2025
  - start_day: 26/11/2025
  - start_day: 03/12/2025
  - start_day: 10/12/2025
  - start_day: 17/12/2025
  - start_day: 07/01/2026
  - start_day: 14/01/2026
  - start_day: 21/01/2026
  - start_day: 28/01/2026
  - start_day: 04/02/2026
  - start_day: 11/02/2026
  - start_day: 04/03/2026
  - start_day: 11/03/2026
  - start_day: 18/03/2026
  - start_day: 25/03/2026
  - start_day: 01/04/2026
  - start_day: 08/04/2026
  - start_day: 29/04/2026
  - start_day: 06/05/2026
  - start_day: 13/05/2026
  - start_day: 20/05/2026
  - start_day: 27/05/2026
  - start_day: 03/06/2026
  - start_day: 10/06/2026

thursday_days: &thursday_days
  - start_day: 18/09/2025
  - start_day: 25/09/2025
  - start_day: 02/10/2025
  - start_day: 09/10/2025
  - start_day: 16/10/2025
  - start_day: 06/11/2025
  - start_day: 20/11/2025
  - start_day: 27/11/2025
  - start_day: 04/12/2025
  - start_day: 11/12/2025
  - start_day: 18/12/2025
  - start_day: 08/01/2026
  - start_day: 15/01/2026
  - start_day: 22/01/2026
  - start_day: 29/01/2026
  - start_day: 05/02/2026
  - start_day: 12/02/2026
  - start_day: 05/03/2026
  - start_day: 12/03/2026
  - start_day: 19/03/2026
  - start_day: 26/03/2026
  - start_day: 02/04/2026
  - start_day: 09/04/2026
  - start_day: 30/04/2026
  - start_day: 07/05/2026
  - start_day: 14/05/2026
  - start_day: 21/05/2026
  - start_day: 28/05/2026
  - start_day: 04/06/2026
  - start_day: 11/06/2026

holiday_training_days: &holiday_training_days
  - start_day: 23/10/2025
  - start_day: 30/10/2025
  - start_day: 13/11/2025
  - start_day: 19/02/2027
  - start_day: 26/02/2026
  - start_day: 16/04/2026
  - start_day: 23/04/2026

credentials_file: credentials.bcs.json
categories:

  #
  # Level 3
  #
  initiations_level3:
    calendar: c_9a5896738f84440f8dfeeb5e4336b6c7fe98e52d46001ede08c6bbd4db9f96f3@group.calendar.google.com
    default:
      title: "[Rennes][BCS] Initiation + Soirée 100% WCS"
      location: LEVEL3, 1 rue Jeanne Malivel, Val D'Orson, 35770, 35770 Vern-sur-Seiche, France
      duration: 285 # 4h45 in minutes
      start_time: 20h00
      description: |
        Venez découvrir le West Coast Swing le temps d'une initiation, et pratiquer avec la communauté pendant la soirée qui suit.
        Seul·e ou à plusieurs, venez découvrir votre future activité !

        Initiation (20h - 21h30) + Soirée (21h30 - 00h45) -  6€, 1 conso offerte.

        Inscription sur https://level3.audrei.net/events/8696192341af1c1f79548efdb1a2a698
    items:
      - start_day: 30/08/2025
      - start_day: 23/05/2026
      - start_day: 27/06/2026

  ateliers_level3:
    calendar: c_9a5896738f84440f8dfeeb5e4336b6c7fe98e52d46001ede08c6bbd4db9f96f3@group.calendar.google.com
    default:
      title: "[Rennes][BCS] Atelier + Soirée 100% WCS"
      location: LEVEL3, 1 rue Jeanne Malivel, Val D'Orson, 35770, 35770 Vern-sur-Seiche, France
      duration: 285 # 4h45 in minutes
      start_time: 20h00
      description: |
        Atelier (20h - 21h30) + Soirée (21h30 - 00h45) -  10€, 1 conso offerte. Soirée seule à 6€ avec une conso.

        Informations sur les niveaux / thèmes à venir.

        Inscription sur https://level3.audrei.net/events/8696192341af1c1f79548efdb1a2a698
    items:
      - start_day: 27/09/2025 # A & C
      - start_day: 18/10/2025 # F & M
      - start_day: 22/11/2025 #
      - start_day: 10/01/2026
      - start_day: 31/01/2026
      - start_day: 14/02/2026
      - start_day: 21/03/2026
        title: "[A Confirmer] Atelier + Soirée 100% WCS"
      - start_day: 25/04/2026

  dds:
    calendar: c_9a5896738f84440f8dfeeb5e4336b6c7fe98e52d46001ede08c6bbd4db9f96f3@group.calendar.google.com
    default:
      title: "[Rennes][BCS] Dirty Dance Swing"
      location: Salle du Bocage, Prom. Henri Verger, 35410 Nouvoitou, France
      duration: 2880 # 2 days
      start_time: 20h00
      description: |
        Informations à venir
    items:
      - start_day: 07/11/2025
  #
  # Mardi
  #
  cours_n1_mardi:
    calendar: c_2cccf505e636ee3a357a381b7ee1ad1b8e25d14fcbca9498928356b3de514b0c@group.calendar.google.com
    default:
      title: Cours niveau 1 - Mardi
      location: Maison de Quartier La Touche, 6 Rue Cardinal Paul Gouyon, 35000 Rennes, France
      duration: 60
      start_time: 20h30
      description: |
        Cours niveau 1
        Ce cours est précédé de 15 minutes de pratique en commun avec le niveau 3.
        Vous êtes encouragé·e·s à arriver dès 20h15 !

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *tuesday_days

  cours_n2_mardi:
    calendar: c_35650dd62f4cdcfe486dcfe1fd483ecdc662279e7dab49ee9363bd1beb127fee@group.calendar.google.com
    default:
      title: Cours niveau 2 - Mardi
      location: Maison de Quartier La Touche, 6 Rue Cardinal Paul Gouyon, 35000 Rennes, France
      duration: 60
      start_time: 21h30
      description: |
        Cours niveau 2

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *tuesday_days

  cours_n3_mardi:
    calendar: c_78df50123aed593ccac54f57c0d49f2ad6dbda434c6d026065e0f7c4c2244a62@group.calendar.google.com
    default:
      title: Cours niveau 3 - Mardi
      location: Maison de Quartier La Touche, 6 Rue Cardinal Paul Gouyon, 35000 Rennes, France
      duration: 60
      start_time: 19h15
      description: |
        Cours niveau 3
        Ce cours est suivi de 15 minutes de pratique en commun avec le niveau 1.

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *tuesday_days

  #
  # Mercredi
  #
  cours_n1_mercredi:
    calendar: c_882abc9dc3d2cafbd3a29c865059a50b9b285736d0708e8156a726498d438b94@group.calendar.google.com
    default:
      title: Cours niveau 1 - Mercredi
      location: La Cabane, 12 Rte des Parcs Quercie, 35510 Cesson-Sévigné, France
      duration: 60
      start_time: 19h15
      description: |
        Cours niveau 1
        Ce cours est suivi de 15 minutes de pratique en commun avec le niveau 2.

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *wednesday_days

  cours_n2_mercredi:
    calendar: c_7c9177815e59230da75c64630e7179019b1102a7429c7552bf4fbc59de463013@group.calendar.google.com
    default:
      title: Cours niveau 2 - Mercredi
      location: La Cabane, 12 Rte des Parcs Quercie, 35510 Cesson-Sévigné, France
      duration: 60
      start_time: 20h30
      description: |
        Cours niveau 2
        Ce cours est précédé de 15 minutes de pratique en commun avec le niveau 1.
        Vous êtes encouragé·e·s à arriver dès 20h15 !

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *wednesday_days

  cours_n4_mercredi:
    calendar: c_ecc63465282d2b033399cffc03699e5fee0a094d8b6a85cfadc3b96f39447f53@group.calendar.google.com
    default:
      title: Cours niveau 4 - Mercredi
      location: La Cabane, 12 Rte des Parcs Quercie, 35510 Cesson-Sévigné, France
      duration: 60
      start_time: 21h30
      description: |
        Cours niveau 4

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *wednesday_days

  #
  # Jeudi
  #
  cours_n3_jeudi:
    calendar: c_f320e8edf07d8c7c4ac14f99cba69447684ba04908664bbadda8fd89130a03c3@group.calendar.google.com
    default:
      title: Cours niveau 3 - Jeudi
      location: Association du Bourg l'Évêque, 16 Rue Papu, 35000 Rennes, France
      duration: 60
      start_time: 19h15
      description: |
        Cours niveau 3
        Ce cours est suivi de 2h d'entrainement libre ouvert aux adhérent·e·s.

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *thursday_days

  entrainement_jeudi_annee:
    calendar: c_27c826c3086f4de1829bac9712eaf60fcca9169438715e1d294e8ee1344fb382@group.calendar.google.com
    default: &entrainement_jeudi
      title: Entrainement libre - Jeudi
      location: Association du Bourg l'Évêque, 16 Rue Papu, 35000 Rennes, France
      duration: 120
      start_time: 20h15
      description: |
        Session de 2h d'entrainement libre ouvert aux adhérent·e·s.
        Ce créneau n'est pas une pratique mais permet à chacun·e de venir s'entrainer sur le sujet qu'iel souhaite.
        Il est recommandé de s'organiser en amont avec d'autres personnes pour s'assurer d'avoir du monde avec qui s'entrainer.

        Tous les détails sur https://www.breizhcoastswing.fr/les-cours/
    items: *thursday_days

  entrainement_jeudi_vacances:
    calendar: c_27c826c3086f4de1829bac9712eaf60fcca9169438715e1d294e8ee1344fb382@group.calendar.google.com
    default:
      <<: *entrainement_jeudi
    items: *holiday_training_days
